import React from "react"
const Tortas = (props) => {
    return (
        <>

            <div className="fondo">

            </div>
            <div className="titulo">
                <h1>
                    Tortas hechas en casa
                </h1>

            </div>


            <div className ="horizontal-parent">
                <div className ="horizontal-child">
                    <div className ="ordenImagen row">

                        <div className ="ImagenFoto column">
                            <div className ="ImagenFotoInterior">
                                <img src="IMG/bowni.jpeg" alt=""/>
                                    <p>nombre de la torta</p>

                            </div>
                        </div>

                        <div className ="ImagenFoto column">
                            <div className ="ImagenFotoInterior">
                                <img src="IMG/browni top.jpeg" alt=""/>
                                    <p>nombre de la torta</p>

                            </div>
                        </div>
                        <div className ="ImagenFoto column">
                            <div className ="ImagenFotoInterior">
                                <img src="IMG/lemon top.jpeg" alt=""/>
                                    <p>nombre de la torta</p>

                            </div>
                        </div>
                        <div className ="ImagenFoto column">
                            <div className ="ImagenFotoInterior">
                                <img src="IMG/lemon.jpeg" alt=""/>
                                    <p>nombre de la torta</p>

                            </div>
                        </div>
                        <div className ="ImagenFoto column">
                            <div className ="ImagenFotoInterior">
                                <img src="IMG/bowni.jpeg" alt="" />
                                    <p>nombre de la torta</p>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </>
    )
}
export default Tortas;